### ISSUE TITLE
Feature: FLY tag

### ISSUE THREAD

**Issue by Belladonna993** [Ludovicus-Maior/WoW-Pro-Guides#454]
Proposal 

1. Potentially create a FLY tag that is able to check whether a player can fly in the current zone. The tag would cause a step to autocomplete if a player is able to fly.

2. Do not use this tag on F steps. Instead, create a UI toggle that enables or disables F steps.

**Comment by Emmaleah** [comment]
The logic behind this . as opposed to a spell tag is 
1) so can be done before spell id is known (i.e. now, while writing guides, rather than when pathfinder II is released in 6+months.
2)authors don't have to know the spell id for each of the expansions, the parser takes care of that, and we only have to know one tag.

**Comment by Belladonna993** [comment]
And the logic behind making a toggle for F steps instead of using the FLY tag is to give players more options. Some players may occasionally prefer taking flight points even when they can fly.
